steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sahayak-app', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sahayak-app']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sahayak-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sahayak-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'sahayak-cloudrun@sahayak-to-workspace.iam.gserviceaccount.com'
      - '--set-secrets'
      - 'SECRET_KEY=flask-secret-key:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,GEMINI_API_KEY=gemini-api-key:latest,FIREBASE_PRIVATE_KEY_ID=firebase-private-key-id:latest,FIREBASE_PRIVATE_KEY=firebase-private-key:latest,FIREBASE_CLIENT_EMAIL=firebase-client-email:latest,FIREBASE_CLIENT_ID=firebase-client-id:latest,FIREBASE_CLIENT_CERT_URL=firebase-client-cert-url:latest'
      - '--set-env-vars'
      - 'OAUTH_REDIRECT_URI=https://sahayak-app-xxxxxxxxx-uc.a.run.app/auth'

images:
  - 'gcr.io/$PROJECT_ID/sahayak-app' 